# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IjLVruyI-2xeVEtr7tKuCM_ilWWDzw2O
"""

import csv
import os

# =====================================================================
# THE SYSTEM UNDER TEST (A Simple Event Ticketing Gateway)
# Intentional Behavior Rule: Ages 18-120 pass, under 18 fail.
# Negative values or text inputs should be caught gracefully.
# =====================================================================
def validate_ticket_holder(age_input) -> str:
    """
    Evaluates entry eligibility based on age criteria rules.
    """
    try:
        # Convert input to integer
        age = int(age_input)

        # Operational criteria logic checks
        if age < 0 or age > 120:
            return "REJECTED: Out-of-bounds numerical age limit"
        elif age >= 18:
            return "ALLOWED: Criteria fully met"
        else:
            return "REJECTED: Underage barrier exception"

    except ValueError:
        return "ERROR: Non-numeric data type detected"

# =====================================================================
# AUTOMATED VALIDATION LOG ENGINE
# =====================================================================
LOG_FILENAME = "validation_log.csv"

def initialize_log_file():
    """Creates the validation spreadsheet with column headers if missing."""
    if not os.path.exists(LOG_FILENAME):
        with open(LOG_FILENAME, mode='w', newline='', encoding='utf-8') as file:
            writer = csv.writer(file)
            writer.writerow(["Test ID", "Test Category", "Input Data", "Expected Outcome", "Actual Result", "Status"])
        print(f"📁 Initialised clean audit log spreadsheet: {LOG_FILENAME}")

def append_validation_record(test_id, category, input_data, expected, actual, status):
    """Appends a new verification row to the CSV file record."""
    with open(LOG_FILENAME, mode='a', newline='', encoding='utf-8') as file:
        writer = csv.writer(file)
        writer.writerow([test_id, category, input_data, expected, actual, status])
    print(f"Step recorded successfully into tracking log.")

# =====================================================================
# INTERACTIVE TESTING HARNESS INTERFACE
# =====================================================================
def main():
    initialize_log_file()
    print("\n================== QA VALIDATION INTERFACE ==================")
    print("Use this terminal interface to run inputs and compile evidence.")
    print("Type 'exit' at any prompt to terminate the session.")
    print("=============================================================\n")

    test_counter = 1

    while True:
        print(f"--- Running Test Case ID: TC-{test_counter:02d} ---")

        # 1. Gather Test Parameters and Categorization
        print("Select Category: 1. Normal | 2. Edge | 3. Invalid Input")
        cat_choice = input("Choice (1-3) or 'exit': ").strip()
        if cat_choice.lower() == 'exit': break

        cat_map = {"1": "Normal", "2": "Edge", "3": "Invalid Input"}
        category = cat_map.get(cat_choice, "Unknown")

        # 2. Gather Test Assertions
        input_data = input("Enter the Input Data to send to code: ").strip()
        if input_data.lower() == 'exit': break

        expected = input("Enter the Expected Outcome (Your Prediction): ").strip()
        if expected.lower() == 'exit': break

        # 3. Fire Test Against Code Engine and Harvest Actual State
        actual = validate_ticket_holder(input_data)
        print(f"\n⚡ CODE RUNTIME EXECUTION OUTPUT: \"{actual}\"")

        # 4. Compare State to Assign Pass/Fail Verification Score
        print("\nCompare your prediction against the code runtime engine:")
        print(f" -> Expected: {expected}")
        print(f" -> Actual  : {actual}")
        status_choice = input("Does the code match your expected design? (y = PASS / n = FAIL): ").strip().lower()
        if status_choice == 'exit': break

        status = "PASS" if status_choice == 'y' else "FAIL"
        print(f"Result set as: {status} \n")

        # 5. Commit Row Entry Into Spreadsheet Store
        append_validation_record(f"TC-{test_counter:02d}", category, input_data, expected, actual, status)

        test_counter += 1
        print("-" * 60 + "\n")

    print(f"\nSession ended. Share '{LOG_FILENAME}' as your workbook evidence!")

if __name__ == "__main__":
    main()